import './globals.css'
import type { Metadata } from 'next'
import About from './About'
import Header from './Header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`
                        w-full
                        min-h-screen
                        overflow-x-hidden
                        flex
                        flex-col
                        justify-between
                        items-stretch
                        ${inter.className}
                         `}>
        <Header />
        <main>
          {children}
        </main>
        <About />
      </body>
    </html>
  )
}
