import './globals.css'
import type { Metadata } from 'next'
import About from './About'
import Header from './Header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Header />
        <main style={{ minHeight: "CALC(100vh - 64px - 68px)" }}>
          {children}
        </main>
        <About />
      </body>
    </html>
  )
}
